site_name: Cartographie des itinéraires de bus
repo_url: https://github.com/trufi-association/mapping-documentation-french
repo_name: mapping-documentation-french
site_description: Documentation in French for communities along the Trufi Association stream who need to map bus routes for OpenStreetMap.

theme: readthedocs

markdown_extensions:
 - admonition
